definitions:
  models.User:
    type: object
info:
  contact: {}
paths:
  /token:
    post:
      responses: {}
  /user/register:
    post:
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.User'
      responses: {}
swagger: "2.0"
